### ISSUE TITLE
npm-force-resolutions EACCES: permission denied

### ISSUE THREAD

**Issue by anhquan291** [jonoirwinrsa/steps-yarn#25]
### Troubleshooting

- [ ] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 0.0.10
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? NOT APPLICABLE

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Bitrise info

- Build URL: _[Please share the build URL with us](https://app.bitrise.io/build/1d30eb47-6657-41c5-9d21-6ca9e876648a?tab=log)._
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: 

<details>
  <pre>
   
     [4/4] Building fresh packages...
$ npx npm-force-resolutions && patch-package
Error: EACCES: permission denied, open './package-lock.json'
    at Object.openSync (node:fs:594:3)
    at Object.fs [as writeFileSync] (node:fs:2207:35)
    at npm_force_resolutions$core$node_spit (/bitrise/src/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:19:21)
    at switch__2144__auto__ (/bitrise/src/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:167:3)
    at /bitrise/src/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.cljs:167:3
    at npm_force_resolutions$core$state_machine__2145__auto____1 (/bitrise/src/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:818:4)
    at cljs.core.async.impl.ioc-helpers/FN-IDX (/bitrise/src/node_modules/npm-force-resolutions/out/npm_force_resolutions/core.js:834:66)
    at cljs.core.async.impl.ioc-helpers/run-state-machine (/bitrise/src/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:35:23)
    at cljs.core.async.impl.ioc-helpers/run-state-machine-wrapped (/bitrise/src/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:39:6)
    at /bitrise/src/node_modules/npm-force-resolutions/out/cljs/core/async/impl/ioc_helpers.cljs:48:39
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Run: provided yarn command failed: exit status 1
  </pre>
</details>

### Steps to reproduce

1. push build
2. see build fail

Hi guys, We're having an issue with `npm-force-resolutions` in our React Native App. I've separated the App into 2 Apps Android and iOS. However, when we tried to apply `npm-force-resolutions` for fixing some `vulnerabilities`. The iOS build successfully but the Android.
Any suggestions please? Really appreciate it. Thanks. Hope to hear from you guys soon. It's urgent.

The build images are attached below.

<img width="819" alt="Screen Shot 2022-10-13 at 22 23 11" src="https://user-images.githubusercontent.com/17813202/195642292-94e0d402-91a3-4bb9-a53a-1ef99380d815.png">

<img width="1226" alt="Screen Shot 2022-10-13 at 22 23 35" src="https://user-images.githubusercontent.com/17813202/195642243-f452beb6-0ed8-4720-853c-857b7adf6510.png">

**Comment by lay-mand** [comment]
I have the same issue; @anhquan291 did you find a solution?
